### PR TITLE
Fixed Issue Introduced in PR #159

### PR DESCRIPTION
**Pull request by Wulfex**
Looks like I forgot a "!" in my safety check.

I apologize.

### CODE REVIEW

**Comment by w8tcha** [comment]
oOps and i didnt checked the code. Thanks for the update

**Comment by lwilkins** [comment]
@w8tcha Could you publish the latest version to the public registry as the version on there doesn't include this fix?

Thanks

**Comment by w8tcha** [comment]
done

**Comment by lwilkins** [comment]
Thanks @w8tcha 👍

**Pull request merged**
