### PR TITLE
fire custom events, to make the new min/max length logic usable without ...

### PR DESCRIPTION
**Pull request by dominikzogg**
...override callback

### CODE REVIEW

**Comment by Gladhon** [comment]
@mesutcakir what you think about this event trigger as default behavior ?

**Comment by mesutcakir** [comment]
@dominikzogg 
I think it should be left to the user option .Let's add one more feature. Such as force or coercion .

IsForceCharMaxLength=true/false
IsForceParagraphMaxLength=true/false
IsForceWordMaxLength=true/false

If the user wants to bring up this feature. This creates a nice job.

@dominikzogg thank you.

**Comment by dominikzogg** [comment]
Hello @mesutcakir

The only diffrence is, that the default behavior now fires an event on document level, to get an alternative to override the callbacks.

I use it in a way, where i can't override the callbacks (over a symfony bundle), so i got the alternative to listen on a event.

Regards @dominikzogg

**Comment by mesutcakir** [comment]
What is the meaning of this code? I do not know.

document.dispatchEvent(cEvent);

**Comment by mesutcakir** [comment]
OK. It's usable.

I understand you.

@dominikzogg  thank you.
@Gladhon I'am okey.

**Comment by dominikzogg** [comment]
@egeloen do i understood the bundle right, that there is no possibilty to use this plugin without those events?

**Comment by dominikzogg** [comment]
events will be supported from from ie >= 9

**Comment by dominikzogg** [comment]
@w8tcha what do you think?

**Comment by dominikzogg** [comment]
@w8tcha thank you

**Pull request merged**
