### PR TITLE
#169 resolve - Add max paragraphs option

### PR DESCRIPTION
**Pull request by moshfeu**
Also add a demo page.

### CODE REVIEW

**Comment by w8tcha** [comment]
Looks like the implementation is incomplete it only checks if the limit is reached but never if the limit is restored. Also there is no visual indication in the status bar

**Comment by moshfeu** [comment]
@w8tcha Thanks for the response.

> if the limit is restored 

I'm not sure I understand what that means.

> Also there is no visual indication in the status bar

Do you mean a indication like this?

screenshot-w8tcha github io-2018 06 10-10-59-52

**Comment by w8tcha** [comment]
Yes I mean the status bar shown in the screen shot

**Comment by moshfeu** [comment]
@w8tcha pushed fix. Can you take a look?

**Comment by w8tcha** [comment]
>@w8tcha pushed fix. Can you take a look?
It still incomplete and will not work but i add the rest of the code

> BTW, do you get an indication when I push a commit to this PR?
Yes

**Comment by moshfeu** [comment]
Ok. Thanks!

**Pull request merged**
